In [14]:
import pandas as pd
import numpy as np

### Inspection

In [15]:
df = pd.read_csv("heart_disease_uci.csv")

In [ ]:
df.head()

<bound method NDFrame.head of       id  age     sex        dataset               cp  trestbps   chol    fbs  \
0      1   63    Male      Cleveland   typical angina     145.0  233.0   True
1      2   67    Male      Cleveland     asymptomatic     160.0  286.0  False
2      3   67    Male      Cleveland     asymptomatic     120.0  229.0  False
3      4   37    Male      Cleveland      non-anginal     130.0  250.0  False
4      5   41  Female      Cleveland  atypical angina     130.0  204.0  False
..   ...  ...     ...            ...              ...       ...    ...    ...
915  916   54  Female  VA Long Beach     asymptomatic     127.0  333.0   True
916  917   62    Male  VA Long Beach   typical angina       NaN  139.0  False
917  918   55    Male  VA Long Beach     asymptomatic     122.0  223.0   True
918  919   58    Male  VA Long Beach     asymptomatic       NaN  385.0   True
919  920   62    Male  VA Long Beach  atypical angina     120.0  254.0  False

              restecg  thalch  exang  oldpeak        slope   ca  \
0      lv hypertrophy   150.0  False      2.3  downsloping  0.0
1      lv hypertrophy   108.0   True      1.5         flat  3.0
2      lv hypertrophy   129.0   True      2.6         flat  2.0
3              normal   187.0  False      3.5  downsloping  0.0
4      lv hypertrophy   172.0  False      1.4    upsloping  0.0
..                ...     ...    ...      ...          ...  ...
915  st-t abnormality   154.0  False      0.0          NaN  NaN
916  st-t abnormality     NaN    NaN      NaN          NaN  NaN
917  st-t abnormality   100.0  False      0.0          NaN  NaN
918    lv hypertrophy     NaN    NaN      NaN          NaN  NaN
919    lv hypertrophy    93.0   True      0.0          NaN  NaN

                  thal  num
0         fixed defect    0
1               normal    2
2    reversable defect    1
3               normal    0
4               normal    0
..                 ...  ...
915                NaN    1
916                NaN    0
917       fixed defect    2
918                NaN    0
919                NaN    1

[920 rows x 16 columns]>

In [17]:
df.shape

(920, 16)

In [18]:
df.columns

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [20]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

### Cleaning

In [21]:
df = df.drop(columns=['id','dataset'])

In [22]:
df['num'] = df['num'].apply(lambda x: 1 if x > 0 else 0)

In [23]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,Male,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,1
2,67,Male,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [26]:
# Imputing fbs and exang with mode values
df['fbs'].fillna(df['fbs'].mode()[0], inplace=True)
df['exang'].fillna(df['exang'].mode()[0], inplace=True)

In [28]:
#Converting them to int
df['fbs'] = df['fbs'].astype(int)
df['exang'] = df['exang'].astype(int)

In [29]:
df[['fbs', 'exang']].head()

   fbs  exang
0    1      0
1    0      1
2    0      1
3    0      0
4    0      0

In [30]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,Male,typical angina,145.0,233.0,1,lv hypertrophy,150.0,0,2.3,downsloping,0.0,fixed defect,0
1,67,Male,asymptomatic,160.0,286.0,0,lv hypertrophy,108.0,1,1.5,flat,3.0,normal,1
2,67,Male,asymptomatic,120.0,229.0,0,lv hypertrophy,129.0,1,2.6,flat,2.0,reversable defect,1
3,37,Male,non-anginal,130.0,250.0,0,normal,187.0,0,3.5,downsloping,0.0,normal,0
4,41,Female,atypical angina,130.0,204.0,0,lv hypertrophy,172.0,0,1.4,upsloping,0.0,normal,0

In [31]:
cat_cols = ['sex', 'cp', 'restecg', 'slope', 'thal']

In [32]:
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [34]:
df['thal'].isnull().sum()

0

In [35]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [36]:
df.head()

,age,trestbps,chol,fbs,thalch,exang,oldpeak,ca,num,sex_Male,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,1,150.0,0,2.3,0.0,0,True,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,0,108.0,1,1.5,3.0,1,True,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,0,129.0,1,2.6,2.0,1,True,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,0,187.0,0,3.5,0.0,0,True,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,0,172.0,0,1.4,0.0,0,False,True,False,False,False,False,False,True,True,False

In [37]:
df['ca'].isnull().sum()

611

In [38]:
#ca has 611 values missing, which is almost like 66% of the whole data. ca seems to be number of major blood vessels colored by fluoroscopy, which is obtained via an expensive and invasive procedure - which will be recommended only if doctor suspects heart disease. Hence, we can drop this column from the dataset.
df = df.drop(columns=['ca'])

In [39]:
df.head()

,age,trestbps,chol,fbs,thalch,exang,oldpeak,num,sex_Male,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,145.0,233.0,1,150.0,0,2.3,0,True,False,False,True,False,False,False,False,False,False
1,67,160.0,286.0,0,108.0,1,1.5,1,True,False,False,False,False,False,True,False,True,False
2,67,120.0,229.0,0,129.0,1,2.6,1,True,False,False,False,False,False,True,False,False,True
3,37,130.0,250.0,0,187.0,0,3.5,0,True,False,True,False,True,False,False,False,True,False
4,41,130.0,204.0,0,172.0,0,1.4,0,False,True,False,False,False,False,False,True,True,False

In [40]:
df.shape

(920, 18)

In [41]:
df.isnull().sum()

age                          0
trestbps                    59
chol                        30
fbs                          0
thalch                      55
exang                        0
oldpeak                     62
num                          0
sex_Male                     0
cp_atypical angina           0
cp_non-anginal               0
cp_typical angina            0
restecg_normal               0
restecg_st-t abnormality     0
slope_flat                   0
slope_upsloping              0
thal_normal                  0
thal_reversable defect       0
dtype: int64

In [42]:
num_cols = ['trestbps', 'chol', 'thalch', 'oldpeak']
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

In [43]:
df.isnull().sum()

age                         0
trestbps                    0
chol                        0
fbs                         0
thalch                      0
exang                       0
oldpeak                     0
num                         0
sex_Male                    0
cp_atypical angina          0
cp_non-anginal              0
cp_typical angina           0
restecg_normal              0
restecg_st-t abnormality    0
slope_flat                  0
slope_upsloping             0
thal_normal                 0
thal_reversable defect      0
dtype: int64

### EDA